version: '2'
services:
    portfolio-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/portfolio/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=portfolio
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
